### ISSUE TITLE
Does not work with Python 3.6

### ISSUE THREAD

**Issue by abenson** [vilcans/screenplain#47]
Using [Big-Fish.fountain](https://fountain.io/_downloads/Big-Fish.fountain) as a test fountain file, screenplain will not generate any file.

~~~
screenplain --format pdf  ~/Big-Fish.fountain bf.pdf
Traceback (most recent call last):
  File "/usr/bin/screenplain", line 6, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/screenplain/main.py", line 131, in main
    to_pdf(screenplay, output, is_strong=options.strong)
  File "/usr/lib/python3.6/site-packages/screenplain/export/pdf.py", line 277, in to_pdf
    doc.build(story)
  File "/usr/lib/python3.6/site-packages/reportlab/platypus/doctemplate.py", line 1065, in build
    self._endBuild()
  File "/usr/lib/python3.6/site-packages/reportlab/platypus/doctemplate.py", line 1000, in _endBuild
    if getattr(self,'_doSave',1): self.canv.save()
  File "/usr/lib/python3.6/site-packages/reportlab/pdfgen/canvas.py", line 1242, in save
    self._doc.SaveToFile(self._filename, self)
  File "/usr/lib/python3.6/site-packages/reportlab/pdfbase/pdfdoc.py", line 218, in SaveToFile
    f.write(data)
TypeError: write() argument must be str, not bytes
~~~

Same end result with HTML.

~~~
lilac:~% screenplain --format html  ~/Big-Fish.fountain bf.html
Traceback (most recent call last):
  File "/usr/bin/screenplain", line 6, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/screenplain/main.py", line 127, in main
    css_file=options.css, bare=options.bare
  File "/usr/lib/python3.6/site-packages/screenplain/export/html.py", line 185, in convert
    css_file or os.path.join(os.path.dirname(__file__), 'default.css')
  File "/usr/lib/python3.6/site-packages/screenplain/export/html.py", line 197, in convert_full
    '<!DOCTYPE html>\n'
  File "/usr/lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
~~~

Package versions are as follows: 

- python3-3.6.8
- python3-six-1.12.0
- python3-reportlab-3.5.18
- python3-Pillow-5.4.1

Any suggestions?

**Comment by abenson** [comment]
Aha! It only happens with writing to stdout. I don't have a solution but that fixes the blocker from use!
